const Color = require("./Color.js");
const Status = require("./Status.js");
const Emojis = require("./Emojis.js");

const expandedTags = {
  cityNoises: [
    "urban",
    "city",
    "town",
    "street",
    "crowd",
    "traffic",
    "market",
    "hustle",
    "bustle",
  ],
  tavernAmbiance: [
    "pub",
    "bar",
    "inn",
    "tavern",
    "cheers",
    "drinks",
    "mugs",
    "fireplace",
    "rustic",
  ],
  prisonDungeonNoises: [
    "prison",
    "dungeon",
    "cell",
    "scary",
    "chains",
    "echoes",
    "grunts",
    "screams",
    "dark",
    "moody",
  ],
  bossBattleMusic: [
    "battle",
    "fight",
    "combat",
    "boss",
    "adrenaline",
    "intense",
    "epic",
    "showdown",
    "danger",
    "evil",
  ],
  coldSadMusic: [
    "sad",
    "lonely",
    "melancholy",
    "desolate",
    "gloomy",
    "tears",
    "heartbreak",
  ],
  warmHappyMusic: [
    "warm",
    "happy",
    "joyful",
    "uplifting",
    "celebration",
    "cheerful",
    "sunny",
    "sun",
    "sunrise",
    "fun",
    "rise",
    "bright",
  ],
  adventuringTravellingMusic: [
    "adventure",
    "journey",
    "travel",
    "explore",
    "discovery",
    "road",
    "fun",
    "wagon",
    "freedom",
  ],
  ominousMusicMysterious: [
    "ominous",
    "mysterious",
    "eerie",
    "suspenseful",
    "darkness",
    "fills",
    "dark",
    "clouds",
    "uncanny",
    "haunting",
    "mystical",
  ],
  magicalWhimsical: [
    "magical",
    "whimsical",
    "enchanting",
    "fantasy",
    "fairy tale",
    "spellbinding",
    "mystical",
    "peaceful",
    "peace",
  ],
  forestAmbiance: [
    "forest",
    "woods",
    "trees",
    "birds",
    "nature",
    "serene",
    "rustling",
    "calm",
    "tranquil",
  ],
  mountainAmbiance: [
    "mountain",
    "peaks",
    "summit",
    "cliffs",
    "wind",
    "scenic",
    "mountainous",
  ],
  beachAmbiance: [
    "beach",
    "shore",
    "waves",
    "seagulls",
    "breeze",
    "relaxing",
    "seashore",
    "sea",
    "sand",
    "ocean",
  ],
  caveAmbiance: [
    "cave",
    "cavern",
    "echoes",
    "stalactites",
    "darkness",
    "spooky",
    "scary",
    "ominous",
    "mysterious",
    "dark",
    "rocks",
    "rocky",
  ],
  castleAmbiance: [
    "castle",
    "fortress",
    "palace",
    "halls",
    "regal",
    "grandeur",
    "noble",
    "trumpets",
    "royal",
  ],
  villageAmbiance: [
    "village",
    "hamlet",
    "town",
    "market",
    "laughter",
    "livestock",
    "chatter",
    "community",
  ],
  underwaterAmbiance: [
    "underwater",
    "ocean",
    "sea",
    "bubbles",
    "depths",
    "whales",
    "calm",
    "submerged",
  ],
  desertAmbiance: [
    "desert",
    "dunes",
    "oasis",
    "sand",
    "heat",
    "mirage",
    "camels",
    "nomadic",
  ],
  hauntedHouseAmbiance: [
    "haunted",
    "house",
    "creepy",
    "ghostly",
    "moans",
    "shadows",
    "candles",
    "chills",
  ],
  spaceAmbiance: [
    "space",
    "cosmic",
    "stars",
    "silence",
    "vacuum",
    "futuristic",
    "astral",
    "universe",
  ],
  winterWonderlandAmbiance: [
    "winter",
    "snow",
    "ice",
    "frost",
    "aurora",
    "cozy",
    "festive",
    "whimsical",
    "windy",
    "icy",
    "frozen",
    "cold",
    "tundra",
    "snowing",
    "snowfall",
  ],
};

let tags = [];

// Loop through each property of expandedTags
for (let key in expandedTags) {
  // Concatenate the tag array of each property to the tags array
  tags = tags.concat(expandedTags[key]);
}

// Remove duplicate tags if any
tags = Array.from(new Set(tags));

const audioList = [
  {
    id: "city",
    name: "City Ambience",
    tags: expandedTags.cityNoises,
    url: "city.mp3",
    actionDesc: "turn the hustle up?",
  },
  {
    id: "tavern",
    name: "Tavern Ambiance",
    tags: expandedTags.tavernAmbiance,
    url: "tavern.mp3",
    actionDesc: "set the mood?",
  },
  {
    id: "prison",
    name: "Prison/Dungeon Noises",
    tags: expandedTags.prisonDungeonNoises,
    url: "prison.mp3",
    actionDesc: "make it ominous?",
  },
  {
    id: "boss",
    name: "Boss Battle Music",
    tags: expandedTags.bossBattleMusic,
    url: "battle.mp3",
    actionDesc: "amp up the adrenaline?",
  },
  {
    id: "melancholic",
    name: "Cold/Sad Music",
    tags: expandedTags.coldSadMusic,
    url: "melancholic.mp3",
    actionDesc: "set a melancholic tone?",
  },
  {
    id: "happy",
    name: "Warm/Happy Music",
    tags: expandedTags.warmHappyMusic,
    url: "happy.mp3",
    actionDesc: "put a smile on their faces?",
  },
  {
    id: "adventuring",
    name: "Adventuring/Travelling Music",
    tags: expandedTags.adventuringTravellingMusic,
    url: "adventure.mp3",
    actionDesc: "embark on a journey?",
  },
  {
    id: "ominous",
    name: "Ominous/Mysterious Music",
    tags: expandedTags.ominousMusicMysterious,
    url: "ominous.mp3",
    actionDesc: "make it mysterious?",
  },
  {
    id: "magical",
    name: "Magical/Whimsical Music",
    tags: expandedTags.magicalWhimsical,
    url: "adventure.mp3",
    actionDesc: "add a touch of magic?",
  },
  {
    id: "forest",
    name: "Forest Ambiance",
    tags: expandedTags.forestAmbiance,
    url: "forest.mp3",
    actionDesc: "immerse in nature?",
  },
  {
    id: "mountain",
    name: "Mountain Ambiance",
    tags: expandedTags.mountainAmbiance,
    url: "mountain.mp3",
    actionDesc: "feel the mountain air?",
  },
  {
    id: "beach",
    name: "Beach Ambiance",
    tags: expandedTags.beachAmbiance,
    url: "beach.mp3",
    actionDesc: "hit the sandy shores?",
  },
  {
    id: "cave",
    name: "Cave Ambiance",
    tags: expandedTags.caveAmbiance,
    url: "cave.mp3",
    actionDesc: "explore the depths?",
  },
  {
    id: "castle",
    name: "Castle Ambiance",
    tags: expandedTags.castleAmbiance,
    url: "castle.mp3",
    actionDesc: "enter the grand halls?",
  },
  {
    id: "village",
    name: "Village Ambiance",
    tags: expandedTags.villageAmbiance,
    url: "village.mp3",
    actionDesc: "feel the village vibes?",
  },
  {
    id: "underwater",
    name: "Underwater Ambiance",
    tags: expandedTags.underwaterAmbiance,
    url: "underwater.mp3",
    actionDesc: "dive into the depths?",
  },
  {
    id: "desert",
    name: "Desert Ambiance",
    tags: expandedTags.desertAmbiance,
    url: "desert.mp3",
    actionDesc: "get lost in the dunes?",
  },
  {
    id: "haunted",
    name: "Haunted House Ambiance",
    tags: expandedTags.hauntedHouseAmbiance,
    url: "hanuted.mp3",
    actionDesc: "creep them out?",
  },
  {
    id: "space",
    name: "Space Ambiance",
    tags: expandedTags.spaceAmbiance,
    url: "space.mp3",
    actionDesc: "blast off into space?",
  },
  {
    id: "winter",
    name: "Winter Wonderland Ambiance",
    tags: expandedTags.winterWonderlandAmbiance,
    url: "winter.mp3",
    actionDesc: "feel the frosty breeze?",
  },
];

module.exports = {
  Status,
  Color,
  settings: {
    listeningCooldown: 5_500,
    prefixCommands: ["control", "language", "prefix"],
    leaveEmptyVC: 60_000,
    validVoiceKeyWords: ["bot", "bard", "bard"],
  },
  tags: tags,
  audioList: audioList,
  Emojis,
};
